### ISSUE TITLE
Example broken with `ConfigSpace==0.7.1`

### ISSUE THREAD

**Issue by PGijsbers** [fmohr/naiveautoml#20]
MWE (note that this installs pandas, see #19):
```bash
python -m venv venv
source venv/bin/activate
python -m pip install --upgrade pip
python -m pip install naiveautoml
python -m pip install pandas
python example.py
```
python example:
```python
import naiveautoml
import sklearn.datasets
naml = naiveautoml.NaiveAutoML()
X, y = sklearn.datasets.load_iris(return_X_y=True)
naml.fit(X, y)
print(naml.chosen_model)
```
output:
```
Successfully installed pandas-2.0.2 python-dateutil-2.8.2 pytz-2023.3 six-1.16.0 tzdata-2023.3

Traceback (most recent call last):
  File "/Users/pietergijsbers/tmp/example.py", line 5, in <module>
    naml.fit(X, y)
  File "/Users/pietergijsbers/tmp/venv/lib/python3.9/site-packages/naiveautoml/naiveautoml.py", line 503, in fit
    self.choose_algorithms(X, y)
  File "/Users/pietergijsbers/tmp/venv/lib/python3.9/site-packages/naiveautoml/naiveautoml.py", line 253, in choose_algorithms
    pl = self.get_pipeline_for_decision_in_step(step_name, comp, X, y, decisions)
  File "/Users/pietergijsbers/tmp/venv/lib/python3.9/site-packages/naiveautoml/naiveautoml.py", line 176, in get_pipeline_for_decision_in_step
    steps_tmp.append((step_name, build_estimator(comp, None, X, y)))
  File "/Users/pietergijsbers/tmp/venv/lib/python3.9/site-packages/naiveautoml/commons.py", line 216, in build_estimator
    params = {"kernel": config_json.read(json.dumps(comp["params"])).get_hyperparameter("kernel").value}
  File "/Users/pietergijsbers/tmp/venv/lib/python3.9/site-packages/ConfigSpace/read_and_write/json.py", line 444, in read
    _construct_hyperparameter(
  File "/Users/pietergijsbers/tmp/venv/lib/python3.9/site-packages/ConfigSpace/read_and_write/json.py", line 490, in _construct_hyperparameter
    q=hyperparameter["q"],
KeyError: 'q'
```
Resolve by installing older version of configspace:
```
python -m pip install "ConfigSpace<0.7.1"
python example.py
```
output:
```
(venv) pietergijsbers@TUE027303 tmp % python example.py                      
Pipeline(steps=[('data-pre-processor', PowerTransformer()),
                ('feature-pre-processor', FastICA()),
                ('learner', QuadraticDiscriminantAnalysis())])
```

**Comment by fmohr** [comment]
@PGijsbers thanks for the pointer. I can reproduce this one. But this seems like a bug in the `ConfigSpace` project where they have some constant parameter name `q` injected, or am I mistaken?

**Comment by fmohr** [comment]
Apparently this has been fixed but no release exists yet: https://github.com/automl/ConfigSpace/issues/325

**Comment by PGijsbers** [comment]
Didn't look at the specifics of things, just noticed that the old configspace worked 👍
